# home:
#   path: /
#   controller: App\Controller\HomeController::index
#index:
#    path: /Estate
#    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET